---
"apiVersion": "apiextensions.k8s.io/v1beta1"
"kind": "CustomResourceDefinition"
"metadata":
  "name": "eniconfigs.crd.k8s.amazonaws.com"
"spec":
  "group": "crd.k8s.amazonaws.com"
  "names":
    "kind": "ENIConfig"
    "plural": "eniconfigs"
    "singular": "eniconfig"
  "scope": "Cluster"
  "versions":
  - "name": "v1alpha1"
    "served": true
    "storage": true